set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ppc64le)
set(CMAKE_SYSROOT /usr/powerpc64le-unknown-linux-gnu/powerpc64le-unknown-linux-gnu/sysroot/)
set(CMAKE_C_COMPILER powerpc64le-unknown-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER powerpc64le-unknown-linux-gnu-g++)
