set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR loongarch64)
set(CMAKE_SYSROOT /usr/loongarch64-unknown-linux-gnu/loongarch64-unknown-linux-gnu/sysroot/)
set(CMAKE_C_COMPILER loongarch64-unknown-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER loongarch64-unknown-linux-gnu-g++)
