/* Generated automatically by the program `genconstants'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CONSTANTS_H
#define GCC_INSN_CONSTANTS_H

#define TBEGINC_MASK 65288
#define TBEGIN_MASK 65292
#define SIBCALL_REGNUM 1
#define PFPO_OP1_TYPE_SHIFT 8
#define PFPO_OP_TYPE_SD 0x8
#define PFPO_OP_TYPE_SF 0x5
#define PFPO_OP_TYPE_DF 0x6
#define FPR0_REGNUM 16
#define PFPO_CONVERT 0x1000000
#define PFPO_OP0_TYPE_SHIFT 16
#define BASE_REGNUM 13
#define GPR0_REGNUM 0
#define RETURN_REGNUM 14
#define PFPO_OP_TYPE_DD 0x9
#define PFPO_OP_TYPE_TF 0x7
#define CC_REGNUM 33
#define FPR2_REGNUM 18
#define PFPO_OP_TYPE_TD 0xa
#define TP_REGNUM 36

enum unspec {
  UNSPEC_ROUND = 0,
  UNSPEC_ICM = 1,
  UNSPEC_TIE = 2,
  UNSPEC_STRCMPCC_TO_INT = 3,
  UNSPEC_CC_TO_INT = 4,
  UNSPEC_LTREL_OFFSET = 5,
  UNSPEC_LTREL_BASE = 6,
  UNSPEC_POOL_OFFSET = 7,
  UNSPEC_GOTENT = 8,
  UNSPEC_GOT = 9,
  UNSPEC_GOTOFF = 10,
  UNSPEC_PLT = 11,
  UNSPEC_PLTOFF = 12,
  UNSPEC_RELOAD_BASE = 13,
  UNSPEC_MAIN_BASE = 14,
  UNSPEC_LTREF = 15,
  UNSPEC_INSN = 16,
  UNSPEC_EXECUTE = 17,
  UNSPEC_MB = 18,
  UNSPEC_MOVA = 19,
  UNSPEC_TLSGD = 20,
  UNSPEC_TLSLDM = 21,
  UNSPEC_NTPOFF = 22,
  UNSPEC_DTPOFF = 23,
  UNSPEC_GOTNTPOFF = 24,
  UNSPEC_INDNTPOFF = 25,
  UNSPEC_TLSLDM_NTPOFF = 26,
  UNSPEC_TLS_LOAD = 27,
  UNSPEC_SRST = 28,
  UNSPEC_MVST = 29,
  UNSPEC_SP_SET = 30,
  UNSPEC_SP_TEST = 31,
  UNSPEC_TDC_INSN = 32,
  UNSPEC_POPCNT = 33,
  UNSPEC_COPYSIGN = 34
};
#define NUM_UNSPEC_VALUES 35
extern const char *const unspec_strings[];

enum unspecv {
  UNSPECV_BLOCKAGE = 0,
  UNSPECV_TPF_PROLOGUE = 1,
  UNSPECV_TPF_EPILOGUE = 2,
  UNSPECV_POOL = 3,
  UNSPECV_POOL_SECTION = 4,
  UNSPECV_POOL_ALIGN = 5,
  UNSPECV_POOL_ENTRY = 6,
  UNSPECV_MAIN_POOL = 7,
  UNSPECV_SET_TP = 8,
  UNSPECV_CAS = 9,
  UNSPECV_ATOMIC_OP = 10,
  UNSPECV_NOP_2_BYTE = 11,
  UNSPECV_NOP_4_BYTE = 12,
  UNSPECV_NOP_6_BYTE = 13,
  UNSPECV_TBEGIN = 14,
  UNSPECV_TBEGIN_TDB = 15,
  UNSPECV_TBEGINC = 16,
  UNSPECV_TEND = 17,
  UNSPECV_TABORT = 18,
  UNSPECV_ETND = 19,
  UNSPECV_NTSTG = 20,
  UNSPECV_PPA = 21
};
#define NUM_UNSPECV_VALUES 22
extern const char *const unspecv_strings[];

#endif /* GCC_INSN_CONSTANTS_H */
